# setting for service
server:
  port: 8081
  servlet:
    context-path: /aiboot


spring:
  # 配置应用名称
  application:
    name: aiboot

  datasource:
    # mysql
    tomcat:
      initial-size: 10    # 初始化连接数
      max-active: 100     # 最大活跃数
      min-idle: 20        # 最小空闲数
      max-wait: 60000     # 最长等待时间

    # redis
    redis:
      database: 0
      timeout: 5s # 建立连接超时时间
      lettuce:
        pool:
          max-active: 16    # 最大连接数
          max-idle: 12       # 最大空闲连接
          min-idle: 8       # 最小空闲连接
          max-wait: 5000ms  # 获取连接的最大等待时间

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 引入外部配置
  config:
    import: optional:classpath:application-secret.yaml

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: org.aiboot.entity
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    cache-enabled: true                 # 开启缓存
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      db-type: mysql
      id-type: uuid
      fiele-strategy: not_empty
      logic-delete-value: 1
      logic-not-delete-value: 0

#satoken
sa-token:
  token-name: Authorization
  timeout: 259200
  active-timeout: -1
  token-style: uuid
  is-concurrent: false
  is-share: false
  is-log: false

auth:
  prefix-key: "system:user:"
  token-name: Authorization
  timeout: 25920000 # 毫秒（3天）


# AI模型调用
# 火山引擎（deepseek）
ai:
  deepseek:
    model-v3-id: deepseek-v3-250324
    model-r1-id: deepseek-r1-250528
    model-url: https://ark.cn-beijing.volces.com/api/v3/chat/completions